extends: default

rules:
  # https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.brackets
  brackets:
    max-spaces-inside: 1
  # https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.line_length
  line-length:
    max: 88  # profile=black
  # https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.document_start
  document-start:
    present: false
