services:
  db:
    image: postgres:13.4
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${PGUSER:-api}
      - POSTGRES_PASSWORD=${PGPASSWORD:-api}
      - POSTGRES_DB=${PGDATABASE:-api}
    ports:
      # Allow DB access from outside the container
      - "54321:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U twoops_tracker"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    restart: always
    image: redis:6.2
    ports:
      # Allow Redis access from outside the container
      - "63791:6379"

  twoopstracker_app:
    image: codeforafrica/twoopstracker:latest
    depends_on:
      - db
      - redis
    env_file:
      - ./twoops_tracker/.env.template
    volumes:
      - app-media:/app/media
      - app-staticfiles:/app/staticfiles

  twoopstracker:
    image: nginx:1.20
    restart: unless-stopped
    volumes:
      - ./contrib/docker-compose/nginx:/etc/nginx/conf.d
      - app-media:/var/www/media
      - app-staticfiles:/var/www/static
    ports:
      - 8000:80
    depends_on:
      - twoopstracker_app

  pesacheck_meedan_bridge:
    image: codeforafrica/pesacheck_meedan_bridge:latest
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - pesacheck-data:/app/database
    env_file:
      - ./pesacheck_meedan_bridge/.env

volumes:
  app-media:
  app-staticfiles:
  db-data:
  pesacheck-data:
