services:
  db:
    image: postgres:13.4
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${PGUSER:-api}
      - POSTGRES_PASSWORD=${PGPASSWORD:-api}
      - POSTGRES_DB=${PGDATABASE:-api}
    ports:
      # Allow DB access from outside the container
      - "54321:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U twoops_tracker"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    restart: always
    image: redis:6.2
    ports:
      # Allow Redis access from outside the container
      - "63791:6379"

  twoops_tracker:
    image: codeforafrica/twoops-tracker:latest
    depends_on:
      - db
      - redis
    environment:
      - TWOOPSTRACKER_DATABASE_URL=postgres://${PGUSER:-twoops_tracker}:${PGPASSWORD:-twoops_tracker}@db:5432/${PGDATABASE:-twoops_tracker}
      - TWOOPSTRACKER_CELERY_BROKER_URL=${TWOOPSTRACKER_CELERY_BROKER_URL:-redis://redis:6379/0}
    env_file:
      - .env
    volumes:
      - app-staticfiles:/app/staticfiles
  
  nginx:
    image: nginx:1.20
    restart: unless-stopped
    volumes:
      - ./contrib/docker-compose/nginx:/etc/nginx/conf.d
      - app-staticfiles:/var/www/static
    ports:
      - 8000:80
    depends_on:
      - twoops_tracker

volumes:
  db-data:
  app-staticfiles:
