[GLOBAL]
pants_version = "2.13.0"
use_deprecated_directory_cli_args_semantics = false
use_deprecated_pex_binary_run_semantics = false
pythonpath = ["%(buildroot)s/pants-plugins"]

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.experimental.python.lint.pyupgrade",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.docker",
  "pants.backend.docker.lint.hadolint",
  "pants.backend.shell",
  "pants.backend.shell.lint.shellcheck",
  "pants.backend.shell.lint.shfmt",
  "pants.backend.plugin_development",
  "internal_plugins.versioned_setup",
]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = [
  "/dj-cmd/py",
  "/twoops_tracker/docker",
  "/twoops_tracker/py",
  "/twoops_tracker/sh",
  "/pants-plugins",
]

[python]
interpreter_constraints = ["==3.10.*"]

[black]
args = ["--preview"]

[docker]
default_repository = "codeforafrica/{name}"
build_args = ["VERSION"]
