[GLOBAL]
pants_version = "2.23.0"
pythonpath = ["%(buildroot)s/pants-plugins"]

backend_packages.add = [
  "pants.backend.build_files.fmt.ruff",
  "pants.backend.docker",
  "pants.backend.docker.lint.hadolint",
  "pants.backend.plugin_development",
  "pants.backend.python",
  "pants.backend.python.mixed_interpreter_constraints",
  "pants.backend.python.lint.bandit",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.lint.pyupgrade",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.shell",
  "pants.backend.shell.lint.shellcheck",
  "pants.backend.shell.lint.shfmt",
  "pants.backend.tools.taplo",
  # Expiremental backends
  "pants.backend.experimental.python",
  "pants.backend.experimental.python.framework.django",
  "pants.backend.experimental.python.lint.ruff.check",
  "pants.backend.experimental.python.lint.ruff.format",
  "pants.backend.experimental.tools.yamllint",
  # In-repo plugins
  "internal_plugins.versioned_setup",
]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = [
  "/dj-cmd/py",
  "/twoops_tracker/docker",
  "/twoops_tracker/py",
  "/pants-plugins",
  "/pesacheck_meedan_bridge/py",
  "/pesacheck_meedan_bridge/docker",
]

[python]
enable_resolves = false
interpreter_constraints = ["==3.11.*"]

[python-repos]
find_links = ["https://wheels.pantsbuild.org/simple"]

[generate-lockfiles]
diff = true

[bandit]
args = ["--quiet"]

[mypy]
requirements = ["django-stubs"]
interpreter_constraints = ["==3.11.*"]

[pyupgrade]
args = ["--py36-plus"]

[docker]
build_args = ["VERSION"]
default_repository = "codeforafrica/{name}"

[environments-preview.names]
linux = "//:local_linux"
linux_docker = "//:docker_bookworm"
macos = "//:local_macos"
