[GLOBAL]
pants_version = "2.19.0"
pythonpath = ["%(buildroot)s/pants-plugins"]

backend_packages.add = [
  "pants.backend.build_files.fmt.black",
  "pants.backend.docker",
  "pants.backend.docker.lint.hadolint",
  "pants.backend.plugin_development",
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.lint.pyupgrade",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.shell",
  "pants.backend.shell.lint.shellcheck",
  "pants.backend.shell.lint.shfmt",
  "pants.backend.tools.taplo",
  # Expiremental backends
  "pants.backend.experimental.python",
  "pants.backend.experimental.python.framework.django",
  "pants.backend.experimental.tools.yamllint",
  # In-repo plugins
  "internal_plugins.versioned_setup",
]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = [
  "/dj-cmd/py",
  "/twoops_tracker/docker",
  "/twoops_tracker/py",
  "/pants-plugins",
  "/pesacheck_meedan_bridge/py",
  "/pesacheck_meedan_bridge/docker",
  "/content_access_bot/py",
  "/content_access_bot/docker",
]

[python]
interpreter_constraints = ["==3.11.*"]

[black]
args = ["--preview"]

[docker]
build_args = ["VERSION"]
default_repository = "codeforafrica/{name}"

[environments-preview.names]
linux = "//:local_linux"
linux_docker = "//:docker_bookworm"
macos = "//:local_macos"
