FROM python:3.11-slim-bookworm AS python-base

COPY pesacheck_meedan_bridge.py/pesacheck-srcs@environment=linux.pex /pesacheck-srcs.pex
RUN PEX_TOOLS=1 python /pesacheck-srcs.pex venv --scope=srcs --compile /app
