FROM python:3.11-slim-bookworm

COPY content_access_bot.py/content_access_bot-deps@environment=linux.pex /content_access_bot-deps.pex
RUN PEX_TOOLS=1 python /content_access_bot-deps.pex venv --scope=deps --compile /app
