# Generated by Django 3.2.8 on 2021-10-18 09:28
from typing import List

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: List[str] = []

    operations = [
        migrations.CreateModel(
            name="Tweet",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tweet_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("content", models.TextField(help_text="Tweet Content")),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField()),
                ("retweet_id", models.BigIntegerField(null=True)),
                ("retweeted_user_id", models.BigIntegerField(null=True)),
                ("number_of_interactions", models.IntegerField(default=0)),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
    ]
