# Generated by Django 3.2.8 on 2021-10-18 09:28
from typing import List

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: List[str] = []

    operations = [
        migrations.CreateModel(
            name="Tweet",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tweet_id", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "content",
                    models.CharField(max_length=280, help_text="Tweet Content"),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("retweet_id", models.BigIntegerField(null=True)),
                ("retweeted_user_id", models.BigIntegerField(null=True)),
                ("likes_count", models.IntegerField(default=0)),
                ("retweets_count", models.IntegerField(default=0)),
                ("replies_count", models.IntegerField(default=0)),
                ("actual_tweet", models.JSONField()),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
    ]
