# Generated by Django 3.2.8 on 2021-10-20 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twoops", "0001_tweet_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="TwitterAccount",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of Twitter Account", max_length=100
                    ),
                ),
                (
                    "screen_name",
                    models.CharField(
                        help_text="Twitter Account Screen Name", max_length=100
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("protected", models.BooleanField(default=False)),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("followers_count", models.IntegerField()),
                ("friends_count", models.IntegerField()),
                ("favourites_count", models.IntegerField()),
                ("statuses_count", models.IntegerField()),
                ("created_at", models.DateTimeField()),
                ("profile_image_url", models.URLField()),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="tweet",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="twoops.twitteraccount",
            ),
            preserve_default=False,
        ),
    ]
