# Generated by Django 3.2.8 on 2021-11-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twoops", "0006_make_fields_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="retweet_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="retweeted_user_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="twitteraccount",
            name="account_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
