# Generated by Django 3.2.8 on 2021-11-15 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twoops", "0009_tweet_retweeted_user_screen_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TweetSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query", models.JSONField(help_text="Search Query")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="The name of the Search Query",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tweet_searches",
                        to="twoops.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("query", "owner")},
            },
        ),
    ]
