# Generated by Django 3.2.8 on 2021-11-25 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("twoops", "0011_alter_tweetsearch_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TwitterAccountsList",
            new_name="TwitterAccountsLists",
        ),
    ]
