# Generated by Django 3.2.8 on 2021-11-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("twoops", "0013_auto_20211125_1324"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="twitteraccountslist",
            unique_together={("name", "owner")},
        ),
    ]
