# Generated by Django 3.2.8 on 2021-12-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twoops", "0014_alter_twitteraccountslist_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="twitteraccount",
            name="evidence",
            field=models.URLField(
                blank=True,
                help_text="URL to evidence showing that this account can belong to a public list",
                null=True,
            ),
        ),
    ]
