# Generated by Django 3.2.8 on 2021-12-01 03:13
from typing import List

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("twoops", "0011_alter_tweet_content"),
        ("twoops", "0014_alter_twitteraccountslist_unique_together"),
    ]

    operations: List[str] = []
