# Generated by Django 3.2.8 on 2021-12-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twoops", "0018_auto_20211214_0803"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Category Name", max_length=255, unique=True
            ),
        ),
    ]
