# Generated by Django 3.2.11 on 2022-01-10 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twoops", "0019_alter_category_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Name of Account Group", max_length=255),
                ),
                (
                    "accounts_lists",
                    models.ManyToManyField(
                        related_name="account_groups", to="twoops.TwitterAccountsList"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Owner of the group",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="twoops.userprofile",
                    ),
                ),
                (
                    "users_profiles",
                    models.ManyToManyField(
                        related_name="account_groups", to="twoops.UserProfile"
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "owner")},
            },
        ),
    ]
