# Generated by Django 3.2.11 on 2022-02-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twoops', '0020_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteraccount',
            name='profile_image_url_https',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
