# Generated by Django 3.2.8 on 2021-11-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twoops", "0005_add_default_values_for_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twitteraccount",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="twitteraccount",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="twitteraccount",
            name="profile_image_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="twitteraccount",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name of Twitter Account",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="twitteraccount",
            name="account_id",
            field=models.BigAutoField(
                primary_key=True,
                serialize=False,
                auto_created=True,
            ),
        ),
    ]
