# Generated by Django 3.2.8 on 2021-11-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twoops", "0007_allow_fields_to_be_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
