# Generated by Django 3.2.8 on 2021-11-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twoops", "0008_tweet_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="retweeted_user_screen_name",
            field=models.CharField(
                blank=True,
                help_text="Twitter Account Screen Name",
                max_length=255,
                null=True,
            ),
        ),
    ]
