# Generated by Django 3.2.8 on 2021-11-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twoops", "0010_rename_fields_and_add_quote_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="content",
            field=models.CharField(help_text="Tweet Content", max_length=1024),
        ),
    ]
