# Generated by Django 3.2.8 on 2021-11-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twoops", "0011_alter_tweetsearch_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twitteraccountslist",
            name="is_private",
            field=models.BooleanField(default=True),
        ),
    ]
