# Generated by Django 3.2.8 on 2021-11-25 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("twoops", "0012_alter_twitteraccountslist_is_private"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="twitteraccountslist",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="twitteraccountslist",
            unique_together={("name", "owner", "is_private")},
        ),
    ]
