# Generated by Django 3.2.8 on 2021-12-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twoops", "0016_evidence"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Category Name", max_length=255)),
            ],
            options={
                "get_latest_by": "updated_at",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="twitteraccount",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="twitter_accounts", to="twoops.Category"
            ),
        ),
    ]
