# Generated by Django 3.2.8 on 2021-12-14 08:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("twoops", "0017_auto_20211210_0103"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RenameField(
            model_name="twitteraccount",
            old_name="category",
            new_name="categories",
        ),
    ]
