FROM python:3.11-slim-bookworm

COPY twoops_tracker.py/twoopstracker-srcs@environment=linux.pex /twoopstracker-srcs.pex
RUN PEX_TOOLS=1 python /twoopstracker-srcs.pex venv --scope=srcs --compile /app
