FROM python:3.10-slim-bullseye

COPY twoops_tracker.py/twoopstracker-deps.pex /twoopstracker-deps.pex
RUN PEX_TOOLS=1 /usr/local/bin/python3.10 /twoopstracker-deps.pex venv --scope=deps --compile /app
