FROM python:3.11-slim-bookworm

COPY twoops_tracker.py/twoopstracker-deps@environment=linux.pex /twoopstracker-deps.pex
RUN PEX_TOOLS=1 python /twoopstracker-deps.pex venv --scope=deps --compile /app
