name: TwoopsTracker | Continuous Deployment
on:
  push:
    branches:
      - main
    paths:
      - 'twoops_tracker/py/VERSION'
env:
  DOKKU_REMOTE_BRANCH: "master"
  DOKKU_REMOTE_URL: "ssh://dokku@dokku-1.dev.codeforafrica.org/twoopstracker"
  GIT_PUSH_FLAGS: "--force"
  IMAGE_NAME: "codeforafrica/twoopstracker"
  VERSION: cat twoops_tracker/py/VERSION

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint
        run: |
          ./pants lint twoops_tracker/py::

      - name: Format
        run: |
          ./pants fmt twoops_tracker/py::

      - name: Build
        run: |
          ${{ env.VERSION }} ./pants package twoops_tracker/docker/::

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Push to DockerHub
        run: |
          docker push codeforafrica/twoopstracker:${{ env.VERSION }}

      - name: Push to Dokku
        uses: dokku/github-action@v1.3.0
        with:
          branch: ${{ env.DOKKU_REMOTE_BRANCH }}
          git_push_flags: ${{ env.GIT_PUSH_FLAGS }}
          git_remote_url: ${{ env.DOKKU_REMOTE_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
